window.configuracaoBarbearia={
  nome:'Barbearia Prime',slogan:'Seu estilo começa na cadeira.',descricao:'Corte, barba e estilo com atendimento profissional em um ambiente premium.',telefone:'(00) 00000-0000',whatsapp:'5500000000000',email:'contato@barbearia.com',endereco:'Rua Principal, 250 — Centro',cidade:'Cidade — UF',estado:'UF',pais:'Brasil',instagram:'#',facebook:'#',tiktok:'#',agendamento:'#',mapa:'#',horario:'Segunda a sábado, das 09:00 às 19:00',desenvolvedor:'Sua empresa',
  seo:{titulo:'Barbearia Prime | Corte, Barba e Estilo',palavrasChave:'barbearia, corte masculino, barba, barbeiro, estética masculina, agendamento'},
  estatisticas:[{valor:'10+',rotulo:'anos de experiência'},{valor:'5k+',rotulo:'clientes atendidos'},{valor:'4.9/5',rotulo:'avaliação média'},{valor:'98%',rotulo:'clientes que recomendam'}],
  diferenciais:[{titulo:'Profissionais experientes',texto:'Equipe preparada para cortes personalizados.'},{titulo:'Atendimento personalizado',texto:'Cada cliente recebe atenção ao seu estilo.'},{titulo:'Ambiente confortável',texto:'Um espaço pensado para desacelerar.'},{titulo:'Produtos profissionais',texto:'Produtos selecionados para cabelo e barba.'},{titulo:'Agendamento fácil',texto:'Reserve seu horário de forma rápida.'},{titulo:'Qualidade garantida',texto:'Compromisso com excelência.'}],
  avaliacoes:[{nome:'Cliente satisfeito',nota:5,texto:'Atendimento impecável e corte exatamente como eu queria.'},{nome:'Cliente recorrente',nota:5,texto:'Ambiente excelente, equipe atenciosa e resultado consistente.'},{nome:'Cliente Prime',nota:5,texto:'Virou minha barbearia de confiança. Recomendo muito.'}],
  servicos:[{icone:'✦',nome:'Corte masculino',descricao:'Corte personalizado de acordo com seu estilo.',preco:'R$ 45,00',duracao:'45 min'},{icone:'◈',nome:'Barba',descricao:'Modelagem e acabamento profissional.',preco:'R$ 30,00',duracao:'30 min'},{icone:'✂',nome:'Corte + Barba',descricao:'Experiência completa para renovar seu visual.',preco:'R$ 65,00',duracao:'70 min'},{icone:'◇',nome:'Corte infantil',descricao:'Cortes modernos para os pequenos.',preco:'R$ 35,00',duracao:'35 min'},{icone:'⌁',nome:'Sobrancelha',descricao:'Acabamento e alinhamento.',preco:'R$ 15,00',duracao:'15 min'},{icone:'✧',nome:'Acabamento',descricao:'Finalização rápida para manter o estilo.',preco:'R$ 20,00',duracao:'20 min'}],
  profissionais:[{nome:'Carlos Mendes',descricao:'Especialista em cortes clássicos.',imagem:'https://images.unsplash.com/photo-1621605815971-fbc98d665033?auto=format&fit=crop&w=800&q=80'},{nome:'Rafael Oliveira',descricao:'Especialista em degradês e cortes modernos.',imagem:'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=800&q=80'},{nome:'Lucas Almeida',descricao:'Especialista em barba e visagismo masculino.',imagem:'https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=800&q=80'}],
  precos:[{nome:'Corte',descricao:'Corte masculino personalizado',valor:'R$ 45,00'},{nome:'Barba',descricao:'Modelagem e acabamento',valor:'R$ 30,00'},{nome:'Corte + Barba',descricao:'Experiência completa',valor:'R$ 65,00',destaque:true},{nome:'Infantil',descricao:'Corte para crianças',valor:'R$ 35,00'},{nome:'Sobrancelha',descricao:'Design masculino',valor:'R$ 15,00'}],
  galeria:['https://images.unsplash.com/photo-1521490683712-9c1c0a8e9bfc?auto=format&fit=crop&w=1200&q=80','https://images.unsplash.com/photo-1621605815971-fbc98d665033?auto=format&fit=crop&w=900&q=80','https://images.unsplash.com/photo-1599351431202-1e0f0137899a?auto=format&fit=crop&w=900&q=80','https://images.unsplash.com/photo-1622288432450-277d0fef5ed0?auto=format&fit=crop&w=900&q=80','https://images.unsplash.com/photo-1585747860715-2ba37e788b70?auto=format&fit=crop&w=900&q=80']
};